version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers
      PGDATA: /data/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/data/pgadmin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  eureka-server:
    image: fci2020/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin


  api-gateway:
    image: fci2020/api-gateway:latest
    container_name: api-gateway
    ports:
      - "5055:5055"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server


  fraud:
    image: fci2020/fraud:latest
    container_name: fraud
    ports:
      - "5054:5054"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq


  customers:
    image: fci2020/customers:latest
    container_name: customers
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq


  notifications:
    image: fci2020/notifications:latest
    container_name: notifications
    ports:
      - "5052:5052"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
